name: MergeAndRelease

# Connected workflows are:
# 1. RunTests - run_tests.yml
# 2. CreateReleasePR - create_release_pr.yml
# 3. 📍MergeAndRelease - merge_and_release.yml

# Merges a release PR into main

permissions:
  contents: write
  pull-requests: write
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      sha:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  merge_and_release:
    # Run if the submitted PR is in a branch inside "release/"
    if: github.event_name == 'workflow_call' && startsWith(github.event.inputs.branch, 'release/')

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.sha }}
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Merge PR
        run: |
          PR_NUMBER=$(gh pr list --base main --head ${{ github.event.inputs.branch }} --json number -q '.[0].number')
          gh pr merge $PR_NUMBER --rebase --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        run: |
          gh release create "${{ github.event.inputs.version }}" `
           --target main `
           --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger update in main repo
        run: |
          gh workflow run proxy_update_submodule_refs.yml `
          --repo wookiefriseur/valor-modulis
        env:
          GITHUB_TOKEN: ${{ secrets.VM_ACTIONS }}
