name: RunTests

permissions:
  contents: write
on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize]

jobs:
  run_tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Tests
        id: testresults
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -Confirm:$false -Force
          Invoke-Pester
